Exercise 1

In [7]:
import numpy as np
import math
# Length of a vector
vector = np.array([1,2])
print(vector)

for x in vector:
    print(x)
sum = 0
for x in vector:
    sum = sum + x*x
length = math.sqrt(sum)
print(length)


norm = np.sqrt(np.sum([v**2 for v in vector]))
print(norm)

[1 2]
1
2
2.23606797749979
2.23606797749979


In [8]:
def compute_vector_length (vector):
    len = np.linalg.norm(vector)
    return len
vector = np.array([5,9,-2,-1])
result = compute_vector_length(vector)
print(round(result,2))


10.54


In [16]:
# Dot product
vector1 = np.array([[-1,2],
                    [3,-4]])
vector2 = np.random.rand(2,2)
vector3 = np.random.randint(0,10, (3,4))
print(vector3)

# 2 cách là dùng tọa độ hoặc cos góc xen giữa
def compute_dot_product(vector1,vector2):
    result = np.dot(vector1,vector2)

    return result

# cách 2 dùng @
print("result:\n", vector1@vector2) 

[[5 2 6 1]
 [7 5 9 3]
 [2 8 8 5]]
result:
 [[ 0.17076905  1.5442283 ]
 [-0.17765311 -2.8265856 ]]


In [ ]:
# Multiply matrix with a vector
import numpy as np

def vector_mul_matrix(vector, matrix):
    # Kiểm tra tính hợp lệ của phép nhân (số cột của vector phải bằng số hàng của matrix)
    if vector.shape[1] != matrix.shape[0]:
        raise ValueError("Số cột của vector phải bằng số hàng của ma trận")
    
    # Thực hiện phép nhân
    result = np.dot(vector, matrix)
    return result


import numpy as np

def matrix_mul_matrix(matrix1, matrix2):
    # Kiểm tra tính hợp lệ của phép nhân (số cột của matrix1 phải bằng số hàng của matrix2)
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Số cột của ma trận thứ nhất phải bằng số hàng của ma trận thứ hai")
    
    # Thực hiện phép nhân
    result = np.dot(matrix1, matrix2)
    return result

In [17]:
import numpy as np

def matrix_inverse(matrix):
    # Kiểm tra nếu ma trận là vuông
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Ma trận phải là ma trận vuông để có nghịch đảo")
    
    try:
        # Tính ma trận nghịch đảo
        inverse_matrix = np.linalg.inv(matrix)
        return inverse_matrix
    except np.linalg.LinAlgError:
        raise ValueError("Ma trận này không có nghịch đảo (determinant = 0)")

# Ví dụ sử dụng
matrix = np.array([[1, 2],
                   [3, 4]])

inverse = matrix_inverse(matrix)
print("Matrix:")
print(matrix)
print("Inverse Matrix:")
print(inverse)


Matrix:
[[1 2]
 [3 4]]
Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


Exercise 2


Eigenvector và eigenvalue

Matrix:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
!gdown