In [2]:
import numpy as np

In [8]:
#1
arr = np.arange(10)
print(arr)
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr1 = np.full((3,3), fill_value=True, dtype=bool)
arr2 = np.ones((3,3)) > 0
arr3 = np.ones((3,3), dtype=bool)
print(arr1)
print(arr2)
print(arr3)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [14]:
#3
import numpy as np
arr = np.arange(0,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [18]:
arr = np.arange(0,10)
arr[arr%2 ==1] =-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [19]:
#6
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2],axis =0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
#7
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2],axis =1)
print("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [25]:
#8
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [28]:
#9
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10)) # nếu chỉ có condition thì trẩ về index
print(index)
print("result", a[index])

#một tuple chứa các mảng NumPy (ndarray), 
#mỗi mảng chứa các chỉ số (index) của các phần tử trong mảng thỏa mãn điều kiện.

(array([1, 3, 4], dtype=int64),)
result [ 6  9 10]


In [29]:
import numpy as np 

def maxx(x,y): 
    if x >= y: 
        return x 
    else: 
        return y 

a = np.array([5,7,9,8,6,4,5]) 
b = np.array([6,3,4,8,9,7,1]) 

pair_max = np.vectorize(maxx,otypes=[float]) 
print (pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [30]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

print("Result",np.where(a<b, b, a)) 

#Kết quả trả về là một mảng NumPy (ndarray), 
# chứa các giá trị được chọn từ x hoặc y dựa trên điều kiện.

Result [6 7 9 8 9 7 5]
